import type { NextPage } from 'next';
import Head from 'next/head';

import MenuCard from '../components/Menu/MenuCard';
import { EItemTypes, IMenuItem } from '../components/Menu/MenuTypes';

const menuItems: IMenuItem[] = [
    {
        title: 'Klassieke carpaccio',
        description:
            'In Italië wordt carpaccio geserveerd met olijfolie en citroen. De Nederlandse klassieker eten we het liefst zo: met pijnboompitjes, kaas en rucola.',
        price: {
            value: 11.82,
            currency: '€',
        },
        type: EItemTypes.Starters,
        ingredients: [
            {
                title: 'Balsamicoazijn',
                amount: '½ el',
            },
            {
                title: 'Olijfolie truffelaroma',
                amount: '3 el',
            },
            {
                title: 'Rundercarpaccio',
                amount: '250 g',
            },
            {
                title: 'Rucola',
                amount: '30 g',
            },
            {
                title: 'Parmigiano Reggiano',
                amount: '50 g',
            },
        ],
        totalCalories: 210,
        timeToCook: 10,
        starCount: 3.5,
        ratingCount: 384,
    },
    {
        title: 'Bellini (met perzik uit blik)',
        description:
            'Bellini maken: geen verse perzik, geen probleem! Met perziken op siroop en een vleugje kersenlikeur kun je alsnog een lekkere bellini maken.',
        price: {
            value: 10.14,
            currency: '€',
        },
        type: EItemTypes.Starters,
        ingredients: [
            {
                title: 'Halve perziken op siroop',
                amount: '4',
            },
            {
                title: 'Prosecco',
                amount: '400 mL',
            },
        ],
        totalCalories: 90,
        timeToCook: 10,
        starCount: 3.5,
        ratingCount: 4,
    },
    {
        title: 'Caprese tartaartje',
        description: 'Insalata caprese in een fancy nieuw jasje: als een tartaartje met laagjes.',
        price: {
            value: 11.28,
            currency: '€',
        },
        type: EItemTypes.Starters,
        ingredients: [
            {
                title: 'Tastytom-trostomaten',
                amount: '380 g',
            },
            {
                title: 'Vleestomaten',
                amount: '500 g',
            },
            {
                title: 'Zout',
                amount: '½ tl',
            },
            {
                title: 'Gerookte buffelmozzarella',
                amount: '200 g',
            },
            {
                title: 'Verse basilicum',
                amount: '7.5 g',
            },
            {
                title: 'Extra vierge olijfolie',
                amount: '3 el',
            },
        ],
        totalCalories: 260,
        timeToCook: 30,
        starCount: 4.5,
        ratingCount: 10,
    },
];

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Italiaanse Restaurant</title>
                <meta name='description' content='Generated by create-t3-app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className='container'>
                <MenuCard starterItems={menuItems} />
            </main>
        </>
    );
};

export default Home;
